[features]
seeds = false
skip-lint = false
[programs.localnet]
hello_world_solidity = "B3ajjazFqTpjBV7nyRozAQYScn3HhNGTLnkvvHo5FUo2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/davirain/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
